version: '3.8'
services:
  nextapp:
    image: nextapp
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    networks:
      - dev-network
  nestapp:
    image: nestapp
    environment:
      - NODE_ENV=development
    ports:
      - '3333:3333'
    networks:
      - dev-network
  nginx:
    image: nginx
    ports:
      - '8080:80'
    links:
      - nextapp
      - nestapp
    depends_on:
      - nextapp
      - nestapp
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev-network
networks:
  dev-network:
